import { useMemo, useState } from 'react';
import { CircleDollarSign, Plus, Trash2, X } from 'lucide-react';
import { PRODUCT_CATALOG, PRODUCT_VALIDATION_LABELS } from './product-catalog.mjs';
import { formatDate } from './utils.mjs';
import { blankOpportunity, PRIORITY_CRITERIA, SALES_METHOD_STAGES } from './opportunities-model.mjs';

const OUTCOMES = ['Pendiente', 'Compró', 'Postergó', 'No respondió', 'Eligió competidor', 'Sin encaje', 'Otro'];
const CLOSED_OUTCOMES = new Set(['Compró', 'Eligió competidor', 'Sin encaje']);

function totalFor(item) { return (item.lines || []).reduce((sum, line) => sum + Number(line.quantity || 0) * Number(line.unitPrice || 0), 0); }
function isActive(item) { return !CLOSED_OUTCOMES.has(item.outcome); }
function money(value) { return new Intl.NumberFormat('es-AR', { style: 'currency', currency: 'ARS', maximumFractionDigits: 0 }).format(value || 0); }
function Metric({ label, value }) { return <article className="metric-card"><span>{label}</span><strong>{value}</strong></article>; }

export default function Opportunities({ items, clients, onSave, onDelete }) {
  const [editing, setEditing] = useState(null);
  const [query, setQuery] = useState('');
  const [stage, setStage] = useState('Activas');
  const filtered = useMemo(() => items.filter((item) => {
    const stageMatch = stage === 'Todas' || (stage === 'Activas' ? isActive(item) : item.stage === stage);
    const client = clients.find((entry) => entry.id === item.clientId);
    return stageMatch && `${item.title} ${client?.company || ''} ${item.objection || ''} ${item.priorityCriterion || ''} ${(item.lines || []).map((line) => line.name).join(' ')}`.toLowerCase().includes(query.toLowerCase());
  }), [items, clients, query, stage]);
  const active = items.filter(isActive);
  const activeValue = active.reduce((sum, item) => sum + totalFor(item), 0);
  const weighted = active.reduce((sum, item) => sum + totalFor(item) * Number(item.probability || 0) / 100, 0);
  return <div className="content-stack">
    <section className="metrics-grid opportunity-metrics"><Metric label="Oportunidades activas" value={active.length}/><Metric label="Valor activo" value={money(activeValue)}/><Metric label="Forecast ponderado" value={money(weighted)}/><Metric label="Ganadas" value={items.filter((item) => item.outcome === 'Compró').length}/></section>
    <section className="panel"><div className="panel-head"><div><span className="eyebrow">Ventas en curso</span><h2>Oportunidades y pedidos</h2><p>Las etapas siguen el método comercial de Poliplast.</p></div><button className="primary" onClick={() => setEditing(blankOpportunity())}><Plus size={17}/> Nueva oportunidad</button></div><div className="list-toolbar"><label className="search"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar cliente, objeción o producto…"/></label><select value={stage} onChange={(event) => setStage(event.target.value)}><option>Activas</option><option>Todas</option>{SALES_METHOD_STAGES.map((item) => <option key={item}>{item}</option>)}</select></div><div className="opportunity-list">{filtered.map((item) => { const client = clients.find((entry) => entry.id === item.clientId); return <button className="opportunity-row" key={item.id} onClick={() => setEditing({ ...item, objection: item.objection || '', priorityCriterion: item.priorityCriterion || 'A confirmar', stageHistory: item.stageHistory || [], lines: item.lines || [] })}><div><strong>{item.title || 'Oportunidad sin título'}</strong><span>{client?.company || 'Cliente a confirmar'} · {(item.lines || []).length} productos · {item.priorityCriterion || 'Prioridad a confirmar'}</span></div><span className={`opportunity-stage stage-${item.stage.toLowerCase()}`}>{item.stage}</span><div><strong>{money(totalFor(item))}</strong><span>{item.probability || 0}% · {item.expectedClose ? formatDate(item.expectedClose) : 'sin fecha'}</span></div></button>; })}{!filtered.length && <div className="empty-opportunities"><CircleDollarSign/><p>No hay oportunidades con este filtro.</p></div>}</div></section>
    {editing && <OpportunityModal value={editing} clients={clients} onClose={() => setEditing(null)} onSave={(value) => { onSave(value); setEditing(null); }} onDelete={editing.id ? () => { onDelete(editing.id); setEditing(null); } : null}/>}
  </div>;
}

function OpportunityModal({ value, clients, onClose, onSave, onDelete }) {
  const [form, setForm] = useState(value);
  const update = (name, next) => setForm({ ...form, [name]: next });
  const addLine = () => update('lines', [...(form.lines || []), { id: crypto.randomUUID(), sku: '', name: '', quantity: 1, unit: 'unidad', unitPrice: 0, validation: '' }]);
  const updateLine = (id, changes) => update('lines', form.lines.map((line) => line.id === id ? { ...line, ...changes } : line));
  const chooseProduct = (id, sku) => { const product = PRODUCT_CATALOG.find((item) => item.sku === sku); updateLine(id, product ? { sku, name: product.name, family: product.family, validation: product.validation } : { sku: '', name: '', family: '', validation: '' }); };
  const submit = (event) => { event.preventDefault(); onSave(form); };
  return <div className="modal-backdrop"><form className="modal opportunity-modal" onSubmit={submit}>
    <div className="modal-head"><div><span className="eyebrow">Negocio concreto</span><h2>{form.id ? 'Editar oportunidad' : 'Nueva oportunidad'}</h2><p>Registrá el avance comercial, qué podría comprar y cuál es el próximo paso.</p></div><button type="button" className="icon-button" aria-label="Cerrar oportunidad" onClick={onClose}><X/></button></div>
    <div className="form-grid"><label>Cliente<select required value={form.clientId} onChange={(event) => update('clientId', event.target.value)}><option value="">Seleccionar…</option>{clients.map((client) => <option value={client.id} key={client.id}>{client.company}</option>)}</select></label><label>Título<input required value={form.title} onChange={(event) => update('title', event.target.value)} placeholder="Ej. Reposición EasySpray agosto"/></label><label>Etapa del método<select value={form.stage} onChange={(event) => update('stage', event.target.value)}>{SALES_METHOD_STAGES.map((item) => <option key={item}>{item}</option>)}</select></label><label>Criterio de prioridad<select value={form.priorityCriterion || 'A confirmar'} onChange={(event) => update('priorityCriterion', event.target.value)}>{PRIORITY_CRITERIA.map((item) => <option key={item}>{item}</option>)}</select></label><label>Probabilidad<input type="number" min="0" max="100" value={form.probability} onChange={(event) => update('probability', event.target.value)}/></label><label>Fecha estimada de cierre<input type="date" value={form.expectedClose} onChange={(event) => update('expectedClose', event.target.value)}/></label><label>Resultado<select value={form.outcome} onChange={(event) => update('outcome', event.target.value)}>{OUTCOMES.map((item) => <option key={item}>{item}</option>)}</select></label><label className="span-2">Objeción registrada<input value={form.objection || ''} onChange={(event) => update('objection', event.target.value)} placeholder="Ej. ya tiene proveedor, precio, plazo o falta de decisión"/></label></div>
    <div className="opportunity-products"><div className="section-heading"><div><strong>Productos y cantidades</strong><span>Los precios son de la oportunidad, no del catálogo.</span></div><button type="button" className="secondary" onClick={addLine}><Plus size={16}/> Agregar producto</button></div>{(form.lines || []).map((line) => <div className="product-line" key={line.id}><label>Producto<select value={line.sku} onChange={(event) => chooseProduct(line.id, event.target.value)}><option value="">Seleccionar…</option>{PRODUCT_CATALOG.map((product) => <option disabled={product.validation === 'NoStock'} value={product.sku} key={`${product.sku}-${product.name}`}>{product.name} · {product.sku} · {PRODUCT_VALIDATION_LABELS[product.validation]}</option>)}</select></label><label>Cantidad<input type="number" min="0" step="0.01" value={line.quantity} onChange={(event) => updateLine(line.id, { quantity: event.target.value })}/></label><label>Unidad<input value={line.unit} onChange={(event) => updateLine(line.id, { unit: event.target.value })}/></label><label>Precio unitario<input type="number" min="0" step="0.01" value={line.unitPrice} onChange={(event) => updateLine(line.id, { unitPrice: event.target.value })}/></label><strong>{money(Number(line.quantity || 0) * Number(line.unitPrice || 0))}</strong><button type="button" className="icon-button danger-link" aria-label={`Quitar ${line.name || 'producto'}`} onClick={() => update('lines', form.lines.filter((item) => item.id !== line.id))}><Trash2 size={16}/></button>{line.validation === 'Review' && <span className="product-warning">Producto pendiente de validación comercial.</span>}</div>)}{!(form.lines || []).length && <p className="product-empty">Todavía no agregaste productos.</p>}<div className="opportunity-total"><span>Total estimado</span><strong>{money(totalFor(form))}</strong></div></div>
    <div className="form-grid"><label className="span-2">Próxima acción<input value={form.nextAction} onChange={(event) => update('nextAction', event.target.value)} placeholder="Ej. enviar cotización revisada"/></label><label>Fecha próxima<input type="date" value={form.nextDate} onChange={(event) => update('nextDate', event.target.value)}/></label>{['Eligió competidor', 'Sin encaje', 'Postergó'].includes(form.outcome) && <label>Motivo<input required value={form.lossReason || ''} onChange={(event) => update('lossReason', event.target.value)}/></label>}<label className="span-2">Notas<textarea value={form.notes} onChange={(event) => update('notes', event.target.value)}/></label></div>
    <div className="modal-actions">{onDelete && <button type="button" className="danger-link" onClick={onDelete}>Eliminar oportunidad</button>}<button type="button" className="secondary" onClick={onClose}>Cancelar</button><button className="primary" type="submit">Guardar oportunidad</button></div>
  </form></div>;
}
